#!/bin/bash
trap ":" INT
file="ssl.file"
lines=$(cat $file)


 for ip in $lines
  do
 
 	 mydomain=$(curl -Lsk -o /dev/null -w %{url_effective} http://"$ip" | awk -F / {'print $4'})
     if [[ $mydomain == system ]]; then
         myadobe=$(curl -Lsk -o /dev/null -w %{url_effective} http://"$ip" | awk -F / {'print $3'})
 	 echo $myadobe
 	 echo $myadobe >> urls.txt
     else
         echo $ip
         echo $ip >> ip.txt
     fi 
  done 
  
 
  
